### ISSUE TITLE
From HTTP to HTTPS?

### ISSUE THREAD

**Issue by geoninja** [FlorianWilhelm/FlorianWilhelm.github.io#4]
Hi Florian,

I enjoy your blog, but as many people nowadays, I have set up my machine to block non-secure webpages. Any plans to switch to HTTPS?

**Comment by FlorianWilhelm** [comment]
Hi @geoninja, thanks for this advice. Actually I am not sure how I would do that since I redirect my domain to the github.io page... do you have any clue how I could accomplish this?

**Comment by geoninja** [comment]
Hi @FlorianWilhelm, if your blog was simply hosted on Github, the URL would be https://FlorianWilhelm.github.io. Github pages is a great option for static webpages. However, since you used your own domain (florianwilhelm.info), and if you want to keep this URL, one option would be to buy a SSL certificate from the domain registrar. For example, I have a domain with Namecheap, and this is what they offer: https://www.namecheap.com/security/ssl-certificates.aspx

My own blog (www.aboutdatascience.wordpress.com) is hosted by Wordpress, so they take care of this for me, I didn't have to do the security set up myself (yay!). 

Here is some more info in case you want to dig on this: 
https://en.wikipedia.org/wiki/Transport_Layer_Security
https://support.google.com/webmasters/answer/6073543

**Comment by FlorianWilhelm** [comment]
@geoninja Thanks a lot for the info! I'll look into it. So far I want to keep my own vserver domain in order to be independent of an actual provider, in case I'll change later. I'll check back with my provider.

**Comment by FlorianWilhelm** [comment]
Hi @geoninja, I just migrated my website to https! So welcome back and thanks for raising this issue.
