### ISSUE TITLE
Is UD(A)F more efficient?

### ISSUE THREAD

**Issue by feifanhanmc** [FlorianWilhelm/FlorianWilhelm.github.io#6]
Thank you for this note which helps me a lot. 
But i am still not clear about: Is using UD(A)F more efficient than using only python scripts for data processing ? Why ? Because hive built on the MapReduce ...?

**Comment by FlorianWilhelm** [comment]
It is not more efficient but it scales. If you have a cluster with 100 nodes and 16 cores each your UD(A)F will scale accordingly (depending on your operation of course). If you would use a normal Python script you would get the speed of one core and only by actively using multiprocessing libraries you would be able to leverage maybe the 16 cores of your workstation. This is far away from 100*16 cores. The same goes for RAM. If your data is small enough that you can handle it on one workstation in memory than it's better to not use Hive of course. Check out also Dask if your data is only a few times bigger than the size of your RAM. But if you really have Big Data than Hive or Spark are tools you should think about.
